### ISSUE TITLE
Difficulty in training

### ISSUE THREAD

**Issue by hamedredrose007** [voicepaw/so-vits-svc-fork#1054]
### Describe the bug

(so-vits-svc-fork) PS C:\Users\PC-Kosar\.conda\envs\so-vits-svc-fork> svc pre-resample
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\PC-Kosar\.conda\envs\so-vits-svc-fork\Scripts\svc.exe\__main__.py", line 4, in <module>
  File "C:\Users\PC-Kosar\.conda\envs\so-vits-svc-fork\Lib\site-packages\so_vits_svc_fork\__main__.py", line 9, in <module>
    import click
ModuleNotFoundError: No module named 'click'

When using the command
svc pre-resample
I get the above error

### To Reproduce

When using the command
svc pre-resample
I get the above error

### Version

v4.1.37

### Platform

windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by bcicada** [comment]
In your env type : pip install click

**Comment by hamedredrose007** [comment]
> In your env type : pip install click

Thanks it worked
