### ISSUE TITLE
error when running training

### ISSUE THREAD

**Issue by ruckusmattster** [voicepaw/so-vits-svc-fork#178]
Traceback (most recent call last):
  File "C:\Users\matth\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\matth\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\sovits\venv\Scripts\svc.exe\__main__.py", line 7, in <module>
  File "G:\sovits\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "G:\sovits\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "G:\sovits\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "G:\sovits\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "G:\sovits\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "G:\sovits\venv\lib\site-packages\so_vits_svc_fork\__main__.py", line 115, in train
    train(config_path=config_path, model_path=model_path)
  File "G:\sovits\venv\lib\site-packages\so_vits_svc_fork\train.py", line 49, in train
    mp.spawn(
  File "G:\sovits\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "G:\sovits\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "G:\sovits\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "G:\sovits\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "G:\sovits\venv\lib\site-packages\so_vits_svc_fork\train.py", line 158, in run
    train_and_evaluate(
  File "G:\sovits\venv\lib\site-packages\so_vits_svc_fork\train.py", line 200, in train_and_evaluate
    for batch_idx, items in enumerate(train_loader):
  File "G:\sovits\venv\lib\site-packages\torch\utils\data\dataloader.py", line 634, in __next__
    data = self._next_data()
  File "G:\sovits\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "G:\sovits\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "G:\sovits\venv\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
soundfile.LibsndfileError: <unprintable LibsndfileError object>

im not sure what causes it, i trained once before successfully

**Comment by AngelMiku** [comment]
Were you able to solve this issue @ruckusmattster ? I have the same issue.

**Comment by ruckusmattster** [comment]
ill be honest- dont know what the issue was but i just re downloaded the entire git everytime i needed to train and deletd it after. im sure theres probably some files you have to clean up after each training but i never found it
