### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by KaiserWilheim** [voicepaw/so-vits-svc-fork#198]
**Describe the bug**
```
[23:05:19] PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\gui.py", line 561, in main
    infer(
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\inference_main.py", line 45, in infer
    svc_model = Svc(
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\inference\infer_tool.py", line 108, in __init__
    self.hubert_model = utils.get_hubert_model().to(self.dev)
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\utils.py", line 346, in get_hubert_model
    models, saved_cfg, task = checkpoint_utils.load_model_ensemble_and_task(
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python310\lib\site-packages\fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python310\lib\site-packages\fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**To Reproduce**
Infer using CPU

**Additional context**
My device does not have an available GPU, so I am not sure whether it is about the GPU or not.
I tried to get the newest pytorch, and have made sure that my models are not broken.
I even tried to use a lower version (1.13.1) of pytorch, but the bug was still there.
The program worked fine with an another PC with no GPU, while showing a more simple GUI.
Any hints?
Thanks.

**Comment by KaiserWilheim** [comment]
> Try removing the hubert model manually.

Can't find the hubert model, and reinstalling everything didn't work.

I wonder whether it is OK to ask where do the program download the hubert model in default situations, while using pip to install and using your .bat to install (

**Comment by 34j** [comment]
Calm down and look at the error carefully. Obviously there is no need to reinstall Visual Studio and python. the HuBERT model is in the current directory. BTW, please use venv.

**Comment by KaiserWilheim** [comment]
still cannot work.
I replaced the hubert model with a newly downloaded one, and it still doesn't work.
the error log is still the same:
```
[23:19:41] PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "E:\VITS\venv\lib\site-packages\so_vits_svc_fork\gui.py", line 561, in main
    infer(
  File "E:\VITS\venv\lib\site-packages\so_vits_svc_fork\inference_main.py", line 45, in infer
    svc_model = Svc(
  File "E:\VITS\venv\lib\site-packages\so_vits_svc_fork\inference\infer_tool.py", line 108, in __init__
    self.hubert_model = utils.get_hubert_model().to(self.dev)
  File "E:\VITS\venv\lib\site-packages\so_vits_svc_fork\utils.py", line 346, in get_hubert_model
    models, saved_cfg, task = checkpoint_utils.load_model_ensemble_and_task(
  File "E:\VITS\venv\lib\site-packages\fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "E:\VITS\venv\lib\site-packages\fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "E:\VITS\venv\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "E:\VITS\venv\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```
I put the model in `E:\VITS\venv\Lib\site-packages\so_vits_svc_fork\hubert` and hope that it is the correct place (

**Comment by nickwhite3** [comment]
I'm having the same problem, I'm noob in coding so I'd appreciate if someone could tell how to manually delete and download hubert model

**Comment by 34j** [comment]
```
rm checkpoint_best_legacy_500.pt
```

**Comment by xieyumc** [comment]
Please delete the checkpoint_best_legacy_500.pt(if you are using windows, location: C:\Users\Yourusername),

and reopen svcg to download checkpoint_best_legacy_500.pt,

**Comment by alreadyvla** [comment]
Did you find a solution for this? I have the same error code I just downloaded a model from huggingface and tried. It does not say anything with hubert or so, I am not sure what I should delete there.

**Comment by alreadyvla** [comment]
Also it gives me the same error (PytorchStreamReader failed reading zip archive: failed finding central directory) when i am trying to run svc pre-hubert. In both cases it seems to be a problem with this hubert thing. Also svc -h does not explain what it is. It just says: Preprocessing part 3: hubert If the HuBERT model is not found, it will be... And it literally gives me 3 dots. Do you have any idea what it is or how to fix it?
