### ISSUE TITLE
Expected closing RIGHT_PARENTHESIS and raise_syntax_error

### ISSUE THREAD

**Issue by maisoncastro** [voicepaw/so-vits-svc-fork#222]
**Describe the bug**
When doing the last step for installation, this error comes up:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/maisoncastro/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3105, in _dep_map
    return self.__dep_map
  File "/home/maisoncastro/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2901, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maisoncastro/.local/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "/home/maisoncastro/.local/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/home/maisoncastro/.local/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "/home/maisoncastro/.local/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 120, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "/home/maisoncastro/.local/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 209, in _parse_specifier
    tokenizer.consume("WS")
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/maisoncastro/.local/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 183, in enclosing_tokens
    self.raise_syntax_error(
  File "/home/maisoncastro/.local/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected closing RIGHT_PARENTHESIS
    PyYAML (>=5.1.*)
           ~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 382, in _resolve_one
    set(req_to_install.extras) - set(dist.extras)
  File "/home/maisoncastro/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3061, in extras
    return [dep for dep in self._dep_map if dep]
  File "/home/maisoncastro/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3107, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/maisoncastro/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3117, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/home/maisoncastro/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3170, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/home/maisoncastro/.local/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    PyYAML (>=5.1.*)
           ~~~~~~^
```

**To Reproduce**
Going through Manual Installation, once I input `pip install -U so-vits-svc-fork` the error comes up.

**Additional context**
Windows 11 + WSL

**Comment by Time-consumer** [comment]
I was stuck with this problem, even I tried to change the version of PyYAML. But it doesn't work at all.

**Comment by maisoncastro** [comment]
I fixed it by going through the Windows installation route, rather than the Ubuntu Terminal route, and now everything is working. Still wondering as to why I keep getting the same problem when I install it in my WSL subsystem.
