### ISSUE TITLE
CUDA Weird Erroring all of a sudden.

### ISSUE THREAD

**Issue by Mangio621** [voicepaw/so-vits-svc-fork#402]
I'm currently using paperspace with the A4000 GPU, and have experience in training a few models already. I'm using low batch sizes and samples that are lower than 9 seconds long. However, all of a sudden, when I run "pre-hubert -fm crepe" i'm getting CUDA out of memory errors even though i have a batch size of only 8 and samples are shorter than 9 seconds. 
Here's the traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.9/dist-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/preprocessing/preprocess_hubert_f0.py", line 112, in _process_batch
    _process_one(
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/preprocessing/preprocess_hubert_f0.py", line 49, in _process_one
    f0 = so_vits_svc_fork.f0.compute_f0(
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/f0.py", line 202, in compute_f0
    f0 = compute_f0_crepe(wav_numpy, p_len, sampling_rate, hop_length, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/f0.py", line 170, in compute_f0_crepe
    pitch: Tensor = torchcrepe.predict(
  File "/usr/local/lib/python3.9/dist-packages/torchcrepe/core.py", line 120, in predict
    probabilities = infer(frames, model)
  File "/usr/local/lib/python3.9/dist-packages/torchcrepe/core.py", line 564, in infer
    return infer.model(frames, embed=embed)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torchcrepe/model.py", line 96, in forward
    x = self.embed(x)
  File "/usr/local/lib/python3.9/dist-packages/torchcrepe/model.py", line 120, in embed
    x = self.layer(x, self.conv1, self.conv1_BN, (0, 0, 254, 254))
  File "/usr/local/lib/python3.9/dist-packages/torchcrepe/model.py", line 134, in layer
    return F.max_pool2d(x, (2, 1), (2, 1))
  File "/usr/local/lib/python3.9/dist-packages/torch/_jit_internal.py", line 484, in fn
    return if_false(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/functional.py", line 782, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 736.00 MiB (GPU 0; 15.74 GiB total capacity; 1.54 GiB already allocated; 316.56 MiB free; 2.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/svc", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/__main__.py", line 591, in pre_hubert
    preprocess_hubert_f0(
  File "/usr/local/lib/python3.9/dist-packages/so_vits_svc_fork/preprocessing/preprocess_hubert_f0.py", line 148, in preprocess_hubert_f0
    Parallel(n_jobs=n_jobs)(
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.9/dist-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.9/dist-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 736.00 MiB (GPU 0; 15.74 GiB total capacity; 1.54 GiB already allocated; 316.56 MiB free; 2.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
/usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 4 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**To Reproduce**
Follow the makefile on paperspace up until pre hubert. Run 'svc pre-hubert -fm crepe'. 

**Additional context**
Again, didn't have this issue before...

**Comment by moaazassali** [comment]
I am getting the same error. Have you found any solution?

**Comment by mr-segfault** [comment]
I'm running into a similar issue

**Comment by Mangio621** [comment]
@moaazassali @mr-segfault Good catches! Interesting to know that num of jobs is default 16. Thank you all very much :)
