### ISSUE TITLE
pytorch c extensions failed to load

### ISSUE THREAD

**Issue by AQ206** [voicepaw/so-vits-svc-fork#439]
(venv) C:\Users\hp>svcg
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\hp\venv\Scripts\svcg.exe\__main__.py", line 4, in <module>
  File "C:\Users\hp\venv\lib\site-packages\so_vits_svc_fork\gui.py", line 12, in <module>
    import torch
  File "C:\Users\hp\venv\lib\site-packages\torch\__init__.py", line 443, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

**Comment by zhu-yuefeng** [comment]
Same case.

Details:
    - Env: python 3.10 + Cuda 12.0 (Driver 528.24) + cudNN 8.8.1
    - Action: (PowerScript) .\install.bat
    - Output: 
        - ...
        - Checking cuDNN... cuDNN is not installed.
        - (Action: press some key)
        - ...
        - ```Launching so-vits-svc-fork GUI...
Traceback (most recent call last):
  File "C:\Users\Hi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Hi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\MyPython\voice\so-vits-svc\venv\Scripts\svcg.exe\__main__.py", line 4, in <module>
  File "F:\MyPython\voice\so-vits-svc\venv\lib\site-packages\so_vits_svc_fork\gui.py", line 12, in <module>
    import torch
  File "F:\MyPython\voice\so-vits-svc\venv\lib\site-packages\torch\__init__.py", line 443, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.```

**Comment by AQ206** [comment]
glad i'm not the only one having this problem
