### ISSUE TITLE
How do I fix "KeyError: 'index' (trying to open GUI)?

### ISSUE THREAD

**Issue by KatieBelli** [voicepaw/so-vits-svc-fork#497]
I installed it manually and through the .bat file. After, it opened the GUI. When I want to open it with svcg-command, this appears:

> C:\Users\...>svcg
> [17:23:09] INFO     [17:23:09] version: 3.11.0                                                                                                           gui.py:144
> Traceback (most recent call last):
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\Scripts\svcg.exe\__main__.py", line 7, in <module>
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\so_vits_svc_fork\gui.py", line 554, in main
>     update_devices()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\so_vits_svc_fork\gui.py", line 512, in update_devices
>     ) = get_devices()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\so_vits_svc_fork\gui.py", line 125, in get_devices
>     input_devices_indices = [d["index"] for d in devices if d["max_input_channels"] > 0]
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\so_vits_svc_fork\gui.py", line 125, in <listcomp>
>     input_devices_indices = [d["index"] for d in devices if d["max_input_channels"] > 0]
> KeyError: 'index'

**Comment by kelseyjd** [comment]
I have the same error

**Comment by zsdfaker** [comment]
I debug the code and found that there is no key "index" in the corresponding dict. I changed the "index" directly to the "name" code and it can be run. So far, no problem has been found.
