### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 416: character maps to <undefined>

### ISSUE THREAD

**Issue by Highupech** [voicepaw/so-vits-svc-fork#518]
svc train -t

`Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\Scripts\svc.exe\__main__.py", line 7, in <module>
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\__main__.py", line 129, in train
    train(
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\train.py", line 78, in train
    datamodule = VCDataModule(hparams)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\train.py", line 49, in __init__
    self.train_dataset = TextAudioDataset(self.__hparams, is_validation=False)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\dataset.py", line 22, in __init__
    .read_text()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 416: character maps to <undefined>`

**Comment by 34j** [comment]
@allcontributors add Highupech bug

**Comment by 34j** [comment]
@allcontributors add Highupech bug
