### ISSUE TITLE
Real time inference error

### ISSUE THREAD

**Issue by ThrowawayAccount01** [voicepaw/so-vits-svc-fork#520]
Updated to latest version, 3.11.0 Upon trying to do Real time vc, I get this error:

```
(venv) C:\Users\User\Desktop\sovits\venv\Scripts>svcg
[10:19:30] INFO     [10:19:30] version: 3.11.0                                                                gui.py:144
[10:19:38] INFO     [10:19:38] Event model_path, values {'model_path':                                        gui.py:568
                    'C:/Users/User/Desktop/foxes/mochav3/G_500.pth', 'model_path_browse':
                    'C:/Users/User/Desktop/foxes/mochav3/G_500.pth', 'config_path': '', 'config_path_browse':
                    '', 'cluster_model_path': '', 'cluster_model_path_browse': '', 'speaker': '',
                    'silence_threshold': -35.0, 'transpose': 12.0, 'auto_predict_f0': False, 'f0_method':
                    'dio', 'cluster_infer_ratio': 0.0, 'noise_scale': 0.4, 'pad_seconds': 0.1,
                    'chunk_seconds': 0.5, 'absolute_thresh': True, 'input_path': '', 'input_path_browse': '',
                    'output_path': '', 'output_path_browse': '', 'auto_play': True, 'crossfade_seconds':
                    0.05, 'block_seconds': 0.35, 'additional_infer_before_seconds': 0.15,
                    'additional_infer_after_seconds': 0.1, 'realtime_algorithm': '1 (Divide constantly)',
                    'input_device': 'Microphone (ATR2100x-USB Microp (MME)', 'output_device': 'Headphones
                    (Arctis 5 Game) (MME)', 'passthrough_original': False, 'presets': 'Default VC (GPU, GTX
                    1060)', 'preset_name': '', 'use_gpu': True}
           INFO     [10:19:38] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E4D491670> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
           INFO     [10:19:38] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E4D4B0160> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
           INFO     [10:19:38] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E52D77E20> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
           INFO     [10:19:38] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E52DA5EB0> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
           INFO     [10:19:38] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E52DB1250> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
[10:19:40] INFO     [10:19:40] Event config_path, values {'model_path':                                       gui.py:568
                    'C:/Users/User/Desktop/foxes/mochav3/G_500.pth', 'model_path_browse':
                    'C:/Users/User/Desktop/foxes/mochav3/G_500.pth', 'config_path':
                    'C:/Users/User/Desktop/foxes/mochav3/config.json', 'config_path_browse':
                    'C:/Users/User/Desktop/foxes/mochav3/config.json', 'cluster_model_path': '',
                    'cluster_model_path_browse': '', 'speaker': '', 'silence_threshold': -35.0, 'transpose':
                    12.0, 'auto_predict_f0': False, 'f0_method': 'dio', 'cluster_infer_ratio': 0.0,
                    'noise_scale': 0.4, 'pad_seconds': 0.1, 'chunk_seconds': 0.5, 'absolute_thresh': True,
                    'input_path': '', 'input_path_browse': '', 'output_path': '', 'output_path_browse': '',
                    'auto_play': True, 'crossfade_seconds': 0.05, 'block_seconds': 0.35,
                    'additional_infer_before_seconds': 0.15, 'additional_infer_after_seconds': 0.1,
                    'realtime_algorithm': '1 (Divide constantly)', 'input_device': 'Microphone (ATR2100x-USB
                    Microp (MME)', 'output_device': 'Headphones (Arctis 5 Game) (MME)',
                    'passthrough_original': False, 'presets': 'Default VC (GPU, GTX 1060)', 'preset_name':
                    '', 'use_gpu': True}
           INFO     [10:19:40] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E4D491670> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
           INFO     [10:19:40] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E4D4B0160> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
           INFO     [10:19:40] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E52D77E20> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
           INFO     [10:19:40] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E52DA5EB0> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
           INFO     [10:19:40] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E52DB1250> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
[10:19:42] INFO     [10:19:42] Event cluster_model_path, values {'model_path':                                gui.py:568
                    'C:/Users/User/Desktop/foxes/mochav3/G_500.pth', 'model_path_browse':
                    'C:/Users/User/Desktop/foxes/mochav3/G_500.pth', 'config_path':
                    'C:/Users/User/Desktop/foxes/mochav3/config.json', 'config_path_browse':
                    'C:/Users/User/Desktop/foxes/mochav3/config.json', 'cluster_model_path':
                    'C:/Users/User/Desktop/foxes/mochav3/kmeans.pt', 'cluster_model_path_browse':
                    'C:/Users/User/Desktop/foxes/mochav3/kmeans.pt', 'speaker': 'mochav3',
                    'silence_threshold': -35.0, 'transpose': 12.0, 'auto_predict_f0': False, 'f0_method':
                    'dio', 'cluster_infer_ratio': 0.0, 'noise_scale': 0.4, 'pad_seconds': 0.1,
                    'chunk_seconds': 0.5, 'absolute_thresh': True, 'input_path': '', 'input_path_browse': '',
                    'output_path': '', 'output_path_browse': '', 'auto_play': True, 'crossfade_seconds':
                    0.05, 'block_seconds': 0.35, 'additional_infer_before_seconds': 0.15,
                    'additional_infer_after_seconds': 0.1, 'realtime_algorithm': '1 (Divide constantly)',
                    'input_device': 'Microphone (ATR2100x-USB Microp (MME)', 'output_device': 'Headphones
                    (Arctis 5 Game) (MME)', 'passthrough_original': False, 'presets': 'Default VC (GPU, GTX
                    1060)', 'preset_name': '', 'use_gpu': True}
           INFO     [10:19:42] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E4D491670> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
           INFO     [10:19:42] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E4D4B0160> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
           INFO     [10:19:42] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E52D77E20> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
           INFO     [10:19:42] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E52DA5EB0> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
           INFO     [10:19:42] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x0000015E52DB1250> gui.py:574
                    to C:\Users\User\Desktop\foxes\mochav3
[10:19:55] INFO     [10:19:55] Event start_vc, values {'model_path':                                          gui.py:568
                    'C:/Users/User/Desktop/foxes/mochav3/G_500.pth', 'model_path_browse':
                    'C:/Users/User/Desktop/foxes/mochav3/G_500.pth', 'config_path':
                    'C:/Users/User/Desktop/foxes/mochav3/config.json', 'config_path_browse':
                    'C:/Users/User/Desktop/foxes/mochav3/config.json', 'cluster_model_path':
                    'C:/Users/User/Desktop/foxes/mochav3/kmeans.pt', 'cluster_model_path_browse':
                    'C:/Users/User/Desktop/foxes/mochav3/kmeans.pt', 'speaker': 'mochav3',
                    'silence_threshold': -35.0, 'transpose': 6.0, 'auto_predict_f0': False, 'f0_method':
                    'dio', 'cluster_infer_ratio': 0.5, 'noise_scale': 0.4, 'pad_seconds': 0.1,
                    'chunk_seconds': 0.5, 'absolute_thresh': True, 'input_path': '', 'input_path_browse': '',
                    'output_path': '', 'output_path_browse': '', 'auto_play': False, 'crossfade_seconds':
                    0.05, 'block_seconds': 0.35, 'additional_infer_before_seconds': 0.15,
                    'additional_infer_after_seconds': 0.1, 'realtime_algorithm': '1 (Divide constantly)',
                    'input_device': 'Microphone (ATR2100x-USB Microp (MME)', 'output_device': 'Headphones
                    (Arctis 5 Game) (MME)', 'passthrough_original': False, 'presets': 'Default VC (GPU, GTX
                    1060)', 'preset_name': '', 'use_gpu': True}
[10:19:59] ERROR    [10:19:59] Error in realtime:                                                             gui.py:731
           ERROR    [10:19:59] [WinError 6] The handle is invalid                                             gui.py:732
                    pebble.common.RemoteTraceback: Traceback (most recent call last):
                      File "C:\Users\User\Desktop\sovits\venv\lib\site-packages\pebble\common.py", line 174,
                    in process_execute
                        return function(*args, **kwargs)
                      File
                    "C:\Users\User\Desktop\sovits\venv\lib\site-packages\so_vits_svc_fork\inference\main.py",
                    line 106, in realtime
                        svc_model = Svc(
                      File
                    "C:\Users\User\Desktop\sovits\venv\lib\site-packages\so_vits_svc_fork\inference\core.py",
                    line 109, in __init__
                        self.hubert_model = utils.get_hubert_model(
                      File "C:\Users\User\Desktop\sovits\venv\lib\site-packages\so_vits_svc_fork\utils.py",
                    line 152, in get_hubert_model
                        return HubertModelWithFinalProj.from_pretrained(
                      File
                    "C:\Users\User\Desktop\sovits\venv\lib\site-packages\transformers\modeling_utils.py",
                    line 2269, in from_pretrained
                        config, model_kwargs = cls.config_class.from_pretrained(
                      File
                    "C:\Users\User\Desktop\sovits\venv\lib\site-packages\transformers\configuration_utils.py"
                    , line 546, in from_pretrained
                        config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
                      File
                    "C:\Users\User\Desktop\sovits\venv\lib\site-packages\transformers\configuration_utils.py"
                    , line 573, in get_config_dict
                        config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                      File
                    "C:\Users\User\Desktop\sovits\venv\lib\site-packages\transformers\configuration_utils.py"
                    , line 628, in _get_config_dict
                        resolved_config_file = cached_file(
                      File "C:\Users\User\Desktop\sovits\venv\lib\site-packages\transformers\utils\hub.py",
                    line 409, in cached_file
                        resolved_file = hf_hub_download(
                      File
                    "C:\Users\User\Desktop\sovits\venv\lib\site-packages\huggingface_hub\utils\_validators.py
                    ", line 120, in _inner_fn
                        return fn(*args, **kwargs)
                      File
                    "C:\Users\User\Desktop\sovits\venv\lib\site-packages\huggingface_hub\file_download.py",
                    line 1326, in hf_hub_download
                        http_get(
                      File
                    "C:\Users\User\Desktop\sovits\venv\lib\site-packages\huggingface_hub\file_download.py",
                    line 530, in http_get
                        progress = tqdm(
                      File
                    "C:\Users\User\Desktop\sovits\venv\lib\site-packages\huggingface_hub\utils\tqdm.py", line
                    124, in __init__
                        super().__init__(*args, **kwargs)
                      File "C:\Users\User\Desktop\sovits\venv\lib\site-packages\tqdm\asyncio.py", line 24, in
                    __init__
                        super(tqdm_asyncio, self).__init__(iterable, *args, **kwargs)
                      File "C:\Users\User\Desktop\sovits\venv\lib\site-packages\tqdm\std.py", line 1095, in
                    __init__
                        self.refresh(lock_args=self.lock_args)
                      File "C:\Users\User\Desktop\sovits\venv\lib\site-packages\tqdm\std.py", line 1344, in
                    refresh
                        self.display()
                      File "C:\Users\User\Desktop\sovits\venv\lib\site-packages\tqdm\std.py", line 1492, in
                    display
                        self.sp(self.__str__() if msg is None else msg)
                      File "C:\Users\User\Desktop\sovits\venv\lib\site-packages\tqdm\std.py", line 347, in
                    print_status
                        fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
                      File "C:\Users\User\Desktop\sovits\venv\lib\site-packages\tqdm\std.py", line 340, in
                    fp_write
                        fp.write(str(s))
                      File "C:\Users\User\Desktop\sovits\venv\lib\site-packages\tqdm\utils.py", line 127, in
                    inner
                        return func(*args, **kwargs)
                    OSError: [WinError 6] The handle is invalid


                    The above exception was the direct cause of the following exception:

                    Traceback (most recent call last):
                      File "C:\Users\User\Desktop\sovits\venv\lib\site-packages\so_vits_svc_fork\gui.py",
                    line 729, in main
                        future.result()
                      File
                    "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py",
                    line 439, in result
                        return self.__get_result()
                      File
                    "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py",
                    line 391, in __get_result
                        raise self._exception
                    OSError: [WinError 6] The handle is invalid
```

**Comment by ThrowawayAccount01** [comment]
Downgrading to 3.9.5 makes it work again. Something in the newer versions must have broken it.

**Comment by ThrowawayAccount01** [comment]
To add on, this issue only occurs when using the model on a different pc than the one it was trained on. On the original pc it works on the latest version.

**Comment by ThrowawayAccount01** [comment]
I found out that running through the training process on the fresh install, the error got fixed. Maybe during the steps something important got downloaded which enables the realtime to work properly?

I noticed during the `svc pre-hubert` step, something got downloaded from huggingface. Could these be the files required?

```
(venv) C:\Users\User\Desktop\sovits\venv\Scripts>svc pre-hubert -i "C:\Users\User\Desktop\sovits\venv\Scripts\dataset\hapi" -c "C:\Users\User\Desktop\sovits\venv\Scripts\configs\hapi\config.json" -n 1 -fm crepe
Downloading (…)lve/main/config.json: 100%|█████████████████████████████████████████| 1.39k/1.39k [00:00<00:00, 555kB/s]
[20:22:28] WARNING  [20:22:28]                                                                           warnings.py:109
                    C:\Users\User\Desktop\sovits\venv\lib\site-packages\huggingface_hub\file_download.py
                    :133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to
                    efficiently store duplicated files but your machine does not support them in
                    C:\Users\User\.cache\huggingface\hub. Caching files will still work but in a
                    degraded version that might require more space on your disk. This warning can be
                    disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For
                    more details, see
                    https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
                    To support symlinks on Windows, you either need to activate Developer Mode or to run
                    Python as an administrator. In order to see activate developer mode, see this
                    article:
                    https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-dev
                    elopment
                      warnings.warn(message)

Downloading pytorch_model.bin: 100%|████████████████████████████████████████████████| 378M/378M [00:04<00:00, 88.9MB/s]
```

If this is indeed the case, perhaps making the GUI download these files on first run will help to fix the issue?
