### ISSUE TITLE
Windows 10, svcg - [Errno 13] Permission denied: '.'

### ISSUE THREAD

**Issue by mattopeerenboom** [voicepaw/so-vits-svc-fork#546]
**Describe the bug**
When pressing infer, it does something for a few seconds but then reports a permissions error.

Have tried creating a folder for it to write to with everyone permissions, but doesn't help.

Occurs with both direct install and with Anaconda install

**To Reproduce**
Use windows 10, follow default install instructions

**Additional context**
[16:05:06] INFO     [16:05:06] Event infer, values {'model_path': 'C:/Users/AI/Downloads/svcmodels/Michael Jackson 83k/G_83000.pth', 'model_path_browse':          gui.py:570
                    'C:/Users/AI/Downloads/svcmodels/Michael Jackson 83k/G_83000.pth', 'config_path': '', 'config_path_browse': '', 'cluster_model_path': '',
                    'cluster_model_path_browse': '', 'speaker': '', 'silence_threshold': -35.0, 'transpose': 12.0, 'auto_predict_f0': False, 'f0_method': 'dio',
                    'cluster_infer_ratio': 0.0, 'noise_scale': 0.4, 'pad_seconds': 0.1, 'chunk_seconds': 0.5, 'absolute_thresh': True, 'input_path':
                    'C:/Users/AI/Desktop/mp3split/1_Julia Michaels - Issues_(Vocals).wav', 'input_path_browse': 'C:/Users/AI/Desktop/mp3split/1_Julia Michaels -
                    Issues_(Vocals).wav', 'output_path': 'C:\\Users\\AI\\Desktop\\mp3split\\1_Julia Michaels - Issues_(Vocals).out.wav', 'output_path_browse': '',
                    'auto_play': True, 'crossfade_seconds': 0.05, 'block_seconds': 0.35, 'additional_infer_before_seconds': 0.15,
                    'additional_infer_after_seconds': 0.1, 'realtime_algorithm': '1 (Divide constantly)', 'input_device': '', 'output_device': 'C27F390 (NVIDIA
                    High Definition (MME)', 'passthrough_original': False, 'presets': 'Default VC (GPU, GTX 1060)', 'preset_name': '', 'use_gpu': True}
[16:05:07] INFO     [16:05:07] Starting inference...                                                                                                               gui.py:622
[16:05:11] INFO     [16:05:11] Finished inference for 1_Julia Michaels - Issues_(Vocals).wav                                                                       gui.py:136
           ERROR    [16:05:11] Error opening 'C:/Users/AI/Desktop/mp3split/1_Julia Michaels - Issues_(Vocals).out.wav': System error.                              gui.py:142
                    Traceback (most recent call last):
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\gui.py", line 140, in after_inference
                        play_audio(output_path)
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\gui.py", line 27, in play_audio
                        data, sr = sf.read(path)
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 285, in read
                        with SoundFile(file, 'r', samplerate, channels,
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 658, in __init__
                        self._file = self._open(file, mode_int, closefd)
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 1216, in _open
                        raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
                    soundfile.LibsndfileError: Error opening 'C:/Users/AI/Desktop/mp3split/1_Julia Michaels - Issues_(Vocals).out.wav': System error.
           ERROR    [16:05:11] Error in realtime:                                                                                                                  gui.py:733
           ERROR    [16:05:11] [Errno 13] Permission denied: '.'                                                                                                   gui.py:734
                    pebble.common.RemoteTraceback: Traceback (most recent call last):
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\pebble\common.py", line 174, in process_execute
                        return function(*args, **kwargs)
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\inference\main.py", line 46, in infer
                        svc_model = Svc(
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\inference\core.py", line 105, in __init__
                        self.hps = utils.get_hparams(config_path)
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\utils.py", line 380, in get_hparams
                        config = json.loads(Path(config_path).read_text("utf-8"))
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1134, in read_text
                        with self.open(mode='r', encoding=encoding, errors=errors) as f:
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1119, in open
                        return self._accessor.open(self, mode, buffering, encoding, errors,
                    PermissionError: [Errno 13] Permission denied: '.'

                    The above exception was the direct cause of the following exception:

                    Traceback (most recent call last):
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\gui.py", line 731, in main
                        future.result()
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
                        return self.__get_result()
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
                        raise self._exception
                    PermissionError: [Errno 13] Permission denied: '.'
           ERROR    [16:05:11] Error in inference:                                                                                                                 gui.py:741
           ERROR    [16:05:11] [Errno 13] Permission denied: '.'                                                                                                   gui.py:742
                    pebble.common.RemoteTraceback: Traceback (most recent call last):
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\pebble\common.py", line 174, in process_execute
                        return function(*args, **kwargs)
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\inference\main.py", line 46, in infer
                        svc_model = Svc(
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\inference\core.py", line 105, in __init__
                        self.hps = utils.get_hparams(config_path)
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\utils.py", line 380, in get_hparams
                        config = json.loads(Path(config_path).read_text("utf-8"))
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1134, in read_text
                        with self.open(mode='r', encoding=encoding, errors=errors) as f:
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1119, in open
                        return self._accessor.open(self, mode, buffering, encoding, errors,
                    PermissionError: [Errno 13] Permission denied: '.'

                    The above exception was the direct cause of the following exception:

                    Traceback (most recent call last):
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\gui.py", line 739, in main
                        future.result()
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
                        return self.__get_result()
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
                        raise self._exception
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\gui.py", line 731, in main
                        future.result()
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
                        return self.__get_result()
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
                        raise self._exception
                    PermissionError: [Errno 13] Permission denied: '.'
           ERROR    [16:05:11] Error in realtime:                                                                                                                  gui.py:733
           ERROR    [16:05:11] [Errno 13] Permission denied: '.'                                                                                                   gui.py:734
                    pebble.common.RemoteTraceback: Traceback (most recent call last):
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\pebble\common.py", line 174, in process_execute
                        return function(*args, **kwargs)
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\inference\main.py", line 46, in infer
                        svc_model = Svc(
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\inference\core.py", line 105, in __init__
                        self.hps = utils.get_hparams(config_path)
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\utils.py", line 380, in get_hparams
                        config = json.loads(Path(config_path).read_text("utf-8"))
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1134, in read_text
                        with self.open(mode='r', encoding=encoding, errors=errors) as f:
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1119, in open
                        return self._accessor.open(self, mode, buffering, encoding, errors,
                    PermissionError: [Errno 13] Permission denied: '.'

                    The above exception was the direct cause of the following exception:

                    Traceback (most recent call last):
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\gui.py", line 731, in main
                        future.result()
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
                        return self.__get_result()
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
                        raise self._exception
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\gui.py", line 739, in main
                        future.result()
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
                        return self.__get_result()
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
                        raise self._exception
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\site-packages\so_vits_svc_fork\gui.py", line 731, in main
                        future.result()
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
                        return self.__get_result()
                      File "C:\Users\AI\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
                        raise self._exception
                    PermissionError: [Errno 13] Permission denied: '.'

**Comment by 65rayfos** [comment]
Where did you get the config file from? When I add mine, it just closes svcg

**Comment by LunarCapita1** [comment]
> Worked it out.
> 
> To fix - in the GUI, also need to select a file for the config path. The config file should be in the same directory as the .pth file.
> 
> Recommend the GUI should throw a descriptive error if this selection is empty.

How did you set the config path? I don't have this "config.json" file anywhere needed for this to work, even though I have a pre-trained model.
