### ISSUE TITLE
”AssertionError“ when run command：svc train -t  on M1 MacBook

### ISSUE THREAD

**Issue by jelysen** [voicepaw/so-vits-svc-fork#652]
Traceback (most recent call last):
  File "/Users/shenjingwei/opt/anaconda3/bin/svc", line 8, in <module>
    sys.exit(cli())
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/so_vits_svc_fork/__main__.py", line 128, in train
    train(
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/so_vits_svc_fork/train.py", line 138, in train
    trainer.fit(model, datamodule=datamodule)
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 976, in _run_stage
    self._run_sanity_check()
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1007, in _run_sanity_check
    call._call_callback_hooks(self, "on_sanity_check_end")
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 190, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/Users/shenjingwei/opt/anaconda3/lib/python3.9/site-packages/lightning/pytorch/callbacks/progress/rich_progress.py", line 358, in on_sanity_check_end
    assert self.val_sanity_progress_bar_id is not None
AssertionError

when run command：svc train -t  on M1 MacBook
 returned ”AssertionError“ 
Who can tell me  what happen，TX

**Comment by EDApps3** [comment]
Same issue M2 , did you find a solution?
