### ISSUE TITLE
cannot use svcg

### ISSUE THREAD

**Issue by sungh66** [voicepaw/so-vits-svc-fork#665]
**Describe the bug**
The conda enviroment is OK and i infer my own model what i trained before successfully, but i cannot run the svcg 

Traceback (most recent call last):
  File "/home/anaconda3/envs/so-vits-svc-fork/bin/svcg", line 5, in <module>
    from so_vits_svc_fork.gui import main
  File "/home/anaconda3/envs/so-vits-svc-fork/lib/python3.10/site-packages/so_vits_svc_fork/gui.py", line 10, in <module>
    import sounddevice as sd
  File "/home/anaconda3/envs/so-vits-svc-fork/lib/python3.10/site-packages/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found

**Comment by Agamemnoid** [comment]
sudo apt-get install libportaudio2

Let me know if that works.

**Comment by sungh66** [comment]
> sudo apt-get install libportaudio2
> 
> Let me know if that works.

It works,but how can i improve the model, it sang out of the tune?

**Comment by Agamemnoid** [comment]
1:
I personally run the command
svc pre-hubert -fm crepe

BEFORE training the model. Then during inference I use the crepe auto-predict method.

2:
Train longer. Depending on your dataset. I personally still see improvements up to 1 Million steps. It's definitely diminishing returns, but it does exist.

3:
Better quality target. Not your training dataset, but the song you're inferencing onto. Try another one, clearer, make sure you use vocals only with absolutely no background noise. Make sure it's as clear as possible.

Other than that, you're out of options. It's quite possible that with a shitty dataset you will simply never ever have a good model.
