### ISSUE TITLE
svc infer doesn't work on MacBook Pro M1 (svc train worked successfully)

### ISSUE THREAD

**Issue by devcooch** [voicepaw/so-vits-svc-fork#687]
### Describe the bug

Hey! I am using M1 Mac and trying to get project working on it.
Using `export PYTORCH_ENABLE_MPS_FALLBACK=1` I was able to get `svc train` working.

When running `infer` I get following error:
```
Traceback (most recent call last):
  File "./venv38/bin/svc", line 8, in <module>
    sys.exit(cli())
  File "~/dev/voice/venv38/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "~/dev/voice/venv38/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "~/dev/voice/venv38/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/dev/voice/venv38/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/dev/voice/venv38/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "~/dev/voice/venv38/lib/python3.8/site-packages/so_vits_svc_fork/__main__.py", line 268, in infer
    infer(
  File "~/dev/voice/venv38/lib/python3.8/site-packages/so_vits_svc_fork/inference/main.py", line 95, in infer
    audio = svc_model.infer_silence(
  File "~/dev/voice/venv38/lib/python3.8/site-packages/so_vits_svc_fork/inference/core.py", line 296, in infer_silence
    audio_chunk_pad_infer_tensor, _ = self.infer(
  File "~/dev/voice/venv38/lib/python3.8/site-packages/so_vits_svc_fork/inference/core.py", line 228, in infer
    audio = self.net_g.infer(
  File "~/dev/voice/venv38/lib/python3.8/site-packages/so_vits_svc_fork/modules/synthesizers.py", line 224, in infer
    x, x_mask, f0=f0_to_coarse(f0), noice_scale=noice_scale
  File "~/dev/voice/venv38/lib/python3.8/site-packages/so_vits_svc_fork/f0.py", line 228, in f0_to_coarse
    assert f0_coarse.max() <= 255 and f0_coarse.min() >= 1, (
AssertionError: (tensor(0, device='mps:0'), tensor(0, device='mps:0'))
```

### To Reproduce

Try infer on M1.

### Additional context

Installed using same instructions as in Windows.bat inside Python's virtualenv.
Also tried Python 3.9 and 3.10.

### Version

3.14.1

### Platform

macOS 13.3.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by LandonDeam** [comment]
I have the same issue, svc infer crashes with the following message
`so_vits_svc_fork/f0.py:228 in    │
│ f0_to_coarse                                                                                     │
│                                                                                                  │
│   225 │   f0_mel[f0_mel <= 1] = 1                                                                │
│   226 │   f0_mel[f0_mel > f0_bin - 1] = f0_bin - 1                                               │
│   227 │   f0_coarse = (f0_mel + 0.5).long() if is_torch else np.rint(f0_mel).astype(np.int)      │
│ ❱ 228 │   assert f0_coarse.max() <= 255 and f0_coarse.min() >= 1, (                              │
│   229 │   │   f0_coarse.max(),                                                                   │
│   230 │   │   f0_coarse.min(),                                                                   │
│   231 │   )                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: (tensor(-9223372036854775808, device='cuda:0'), tensor(-9223372036854775808, device='cuda:0'))`

Difference being that I'm on Arch Linux on the latest Kernel (6.3.4.arch1-1), using a 6600XT, and not on Apple Silicon. I'm also running it through Conda on Python 3.10.11. Not sure if there's some strangeness going on with Unix OS's, some strange issue where it tries to find tensors or something, or if there's something else entirely. Like he said above, I cannot use my own model, but I can download and use others' models.

**Comment by devcooch** [comment]
@escoolioinglesias sorry, can't share, it's based on private records.
In the end I did train 92 epochs in free tier of colab, than about 300 epochs more on my Windows laptop.
Then using generate G_*.pth to infer on M1 works fine (both CPU and MPS).
