### ISSUE TITLE
Getting tkinter.TclError: couldn't connect to display ":10.0" in gnome terminal, but works well in xfce terminal

### ISSUE THREAD

**Issue by idkwhodatis** [voicepaw/so-vits-svc-fork#711]
### Describe the bug

My system info:
Ubuntu 22.04.2
Python 3.8.9

Full error info was:
[11:37:55] INFO     [11:37:55] version: 3.15.0                                                                gui.py:160
Traceback (most recent call last):
  File "/home/leaf/proj/sovits-svc/venv/bin/svcg", line 8, in <module>
    sys.exit(main())
  File "/home/leaf/proj/sovits-svc/venv/lib/python3.8/site-packages/so_vits_svc_fork/gui.py", line 544, in main
    window = sg.Window(
  File "/home/leaf/proj/sovits-svc/venv/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 9618, in __init__
    self.Finalize()
  File "/home/leaf/proj/sovits-svc/venv/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 10304, in finalize
    self.Read(timeout=1)
  File "/home/leaf/proj/sovits-svc/venv/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 10079, in read
    results = self._read(timeout=timeout, timeout_key=timeout_key)
  File "/home/leaf/proj/sovits-svc/venv/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 10150, in _read
    self._Show()
  File "/home/leaf/proj/sovits-svc/venv/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 9890, in _Show
    StartupTK(self)
  File "/home/leaf/proj/sovits-svc/venv/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 16821, in StartupTK
    _get_hidden_master_root()
  File "/home/leaf/proj/sovits-svc/venv/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 16708, in _get_hidden_master_root
    Window.hidden_master_root = tk.Tk()
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":10.0"

### To Reproduce

run `svcg`

### Version

3.15.0

### Platform

Ubuntu 22.04.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by idkwhodatis** [comment]
Update to 4.0.1 fixed this issue for me
