### ISSUE TITLE
RuntimeError: tk.h version (8.5) doesn't match libtk.a version (8.6)

### ISSUE THREAD

**Issue by hiwanz** [voicepaw/so-vits-svc-fork#750]
### Describe the bug

```

Traceback (most recent call last):
  File "/Users/hiwanz/.pyenv/versions/3.10.11/bin/svc-gui", line 8, in <module>
    sys.exit(main())
  File "/Users/hiwanz/.pyenv/versions/3.10.11/lib/python3.10/site-packages/so_vits_svc_fork/gui.py", line 544, in main
    window = sg.Window(
  File "/Users/hiwanz/.pyenv/versions/3.10.11/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 9614, in __init__
    self.Finalize()
  File "/Users/hiwanz/.pyenv/versions/3.10.11/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10300, in finalize
    self.Read(timeout=1)
  File "/Users/hiwanz/.pyenv/versions/3.10.11/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10075, in read
    results = self._read(timeout=timeout, timeout_key=timeout_key)
  File "/Users/hiwanz/.pyenv/versions/3.10.11/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10146, in _read
    self._Show()
  File "/Users/hiwanz/.pyenv/versions/3.10.11/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 9886, in _Show
    StartupTK(self)
  File "/Users/hiwanz/.pyenv/versions/3.10.11/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 16817, in StartupTK
    _get_hidden_master_root()
  File "/Users/hiwanz/.pyenv/versions/3.10.11/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 16704, in _get_hidden_master_root
    Window.hidden_master_root = tk.Tk()
  File "/Users/hiwanz/.pyenv/versions/3.10.11/lib/python3.10/tkinter/__init__.py", line 2301, in __init__
    self._loadtk()
  File "/Users/hiwanz/.pyenv/versions/3.10.11/lib/python3.10/tkinter/__init__.py", line 2317, in _loadtk
    raise RuntimeError("tk.h version (%s) doesn't match libtk.a version (%s)"
RuntimeError: tk.h version (8.5) doesn't match libtk.a version (8.6)
```

### To Reproduce

run `svc-gui` in terminal

### Version

3.14.1

### Platform

macOS Ventura V13.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by hiwanz** [comment]
This issue is similar to https://github.com/actions/setup-python/issues/649 , but the solution did not work for me.

**Comment by masakiaota** [comment]
Hi @hiwanz,

Did you try upgrading your Python version? I faced a similar issue. The reason seems to be that `tkinter` (specifically `tk.h`) is a pre-built Python library, and its version appears to be incompatible with `libtk.a`. To upgrade the `tkinter` version, you might want to try upgrading your Python version.

**Comment by hiwanz** [comment]
> Hi @hiwanz,
> 
> Did you try upgrading your Python version? I faced a similar issue. The reason seems to be that `tkinter` (specifically `tk.h`) is a pre-built Python library, and its version appears to be incompatible with `libtk.a`. To upgrade the `tkinter` version, you might want to try upgrading your Python version.

It might work, but I'd like to know if there is any solution that solves the problem with Python <3.11
