### ISSUE TITLE
RuntimeError: Failed to load checkpoint

### ISSUE THREAD

**Issue by sonhm3029** [voicepaw/so-vits-svc-fork#792]
### Describe the bug

```shell
Traceback (most recent call last):
  File "/home/edabk/anaconda3/envs/sovits_3_9/lib/python3.9/site-packages/so_vits_svc_fork/train.py", line 347, in load
    _, _, _, epoch = utils.load_checkpoint(
  File "/home/edabk/anaconda3/envs/sovits_3_9/lib/python3.9/site-packages/so_vits_svc_fork/utils.py", line 264, in load_checkpoint
    checkpoint_dict = torch.load(f, map_location="cpu", weights_only=False)
  File "/home/edabk/anaconda3/envs/sovits_3_9/lib/python3.9/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/edabk/anaconda3/envs/sovits_3_9/lib/python3.9/site-packages/torch/serialization.py", line 1047, in _load
    unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
TypeError: __init__() got an unexpected keyword argument 'weights_only'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/edabk/anaconda3/envs/sovits_3_9/bin/svc", line 8, in <module>
    sys.exit(cli())
  File "/home/edabk/anaconda3/envs/sovits_3_9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/edabk/anaconda3/envs/sovits_3_9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/edabk/anaconda3/envs/sovits_3_9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/edabk/anaconda3/envs/sovits_3_9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/edabk/anaconda3/envs/sovits_3_9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/edabk/anaconda3/envs/sovits_3_9/lib/python3.9/site-packages/so_vits_svc_fork/__main__.py", line 128, in train
    train(
  File "/home/edabk/anaconda3/envs/sovits_3_9/lib/python3.9/site-packages/so_vits_svc_fork/train.py", line 119, in train
    model = VitsLightning(reset_optimizer=reset_optimizer, **hparams)
  File "/home/edabk/anaconda3/envs/sovits_3_9/lib/python3.9/site-packages/so_vits_svc_fork/train.py", line 186, in __init__
    self.load(reset_optimizer)
  File "/home/edabk/anaconda3/envs/sovits_3_9/lib/python3.9/site-packages/so_vits_svc_fork/train.py", line 363, in load
    raise RuntimeError("Failed to load checkpoint") from e
RuntimeError: Failed to load checkpoint

```

I receive this error while running python=3.9.13 with torch version 1.12.1 and cuda-toolkit 11.3.

### To Reproduce

conda create -n sovits python=3.9.13
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
pip install so-vits-svc-fork

train svc

### Version

lastest

### Platform

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by sbersier** [comment]
The weights_only parameter was indeed added in torch==1.13

Personally, I would install it like this:
```
mkdir MySovitsFolder
cd MySovitsFolder
python -m venv venv
source venv/bin/activate  # to activate the venv environnment
pip install -U torch torchaudio

```
In principle, it should install torch==2.0 with everything needed.
You can check that everything is fine with:
`python -c "import torch; print(torch.__version__)"`

Then:
```
pip install -U so-vits-svc-fork
svcg

```
And:
`deactivate # to deactivate the environment`
