### ISSUE TITLE
can't open gui ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by acewins727** [voicepaw/so-vits-svc-fork#820]
### Describe the bug

when I type in svcg it doesn't work, I am using an anaconda environment because otherwise my gpu wasn't detected but now it's just not starting

### To Reproduce

no idea, type in svcg on my machine

### Additional context

(so-vits-svc-fork) C:\Users\maelt>svcg
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\maelt\AppData\Roaming\Python\Python310\Scripts\svcg.exe\__main__.py", line 4, in <module>
  File "C:\Users\maelt\AppData\Roaming\Python\Python310\site-packages\so_vits_svc_fork\gui.py", line 13, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

### Version

4.1.1

### Platform

windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by bugfixer21** [comment]
Try installing torch into the anaconda environment. Use the Anaconda prompt and activate your environment, then, use the command, conda install torch.

**Comment by acewins727** [comment]
that's what i did
