### ISSUE TITLE
Error loading torch_python.dll after installation

### ISSUE THREAD

**Issue by filchcomp** [voicepaw/so-vits-svc-fork#867]
### Describe the bug

Hi all, I have completed manual installation but when I try to launch it, it throws me this error.

My log is here.

(venv) D:\default path>svcg
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\default path\venv\Scripts\svcg.exe\__main__.py", line 4, in <module>
  File "D:\default path\venv\lib\site-packages\so_vits_svc_fork\gui.py", line 13, in <module>
    import torch
  File "D:\default path\venv\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "D:\default path\venv\lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.

(venv) D:\default path>

### To Reproduce

Install python 3.10.11
follow manual installation steps for so-vits-svc-fork on windows.
launch virtual environment and use svcg command.

### Version

v4.1.1

### Platform

Windows 10 64 bit

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by xkeksi** [comment]
any updates on this? looks like it also only happens if python is installed on another SSD instead of the main

**Comment by filchcomp** [comment]
Thanks for the reply, I did not know that it would work once it's installed
on the os drive. Will try to set up an environment there then...
